# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddSpell.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddData(object):
    def setupUi(self, AddData):
        AddData.setObjectName("AddData")
        AddData.resize(558, 487)
        self.centralwidget = QtWidgets.QWidget(AddData)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.inputHTML = QtWidgets.QTextEdit(self.centralwidget)
        self.inputHTML.setObjectName("inputHTML")
        self.gridLayout.addWidget(self.inputHTML, 7, 0, 1, 1)
        self.url = QtWidgets.QLineEdit(self.centralwidget)
        self.url.setObjectName("url")
        self.gridLayout.addWidget(self.url, 1, 0, 1, 1)
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 8, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.school = QtWidgets.QComboBox(self.centralwidget)
        self.school.setObjectName("school")
        self.gridLayout.addWidget(self.school, 5, 0, 1, 1)
        self.displayData = QtWidgets.QTextBrowser(self.centralwidget)
        self.displayData.setObjectName("displayData")
        self.gridLayout.addWidget(self.displayData, 7, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 8, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setObjectName("search")
        self.gridLayout.addWidget(self.search, 1, 1, 1, 2)
        self.subschool = QtWidgets.QComboBox(self.centralwidget)
        self.subschool.setObjectName("subschool")
        self.gridLayout.addWidget(self.subschool, 5, 1, 1, 2)
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 3, 0, 1, 1)
        AddData.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddData)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 21))
        self.menubar.setObjectName("menubar")
        AddData.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(AddData)
        self.statusBar.setObjectName("statusBar")
        AddData.setStatusBar(self.statusBar)

        self.retranslateUi(AddData)
        QtCore.QMetaObject.connectSlotsByName(AddData)
        AddData.setTabOrder(self.url, self.search)
        AddData.setTabOrder(self.search, self.name)
        AddData.setTabOrder(self.name, self.school)
        AddData.setTabOrder(self.school, self.subschool)
        AddData.setTabOrder(self.subschool, self.inputHTML)
        AddData.setTabOrder(self.inputHTML, self.displayData)
        AddData.setTabOrder(self.displayData, self.save)

    def retranslateUi(self, AddData):
        _translate = QtCore.QCoreApplication.translate
        AddData.setWindowTitle(_translate("AddData", "MainWindow"))
        self.save.setText(_translate("AddData", "Save"))
        self.label_6.setText(_translate("AddData", "Input name"))
        self.label_2.setText(_translate("AddData", "Displayed data"))
        self.label_5.setText(_translate("AddData", "Input sub-school"))
        self.label.setText(_translate("AddData", "HTML data"))
        self.label_3.setText(_translate("AddData", "Input URL"))
        self.label_4.setText(_translate("AddData", "Input school"))
        self.search.setText(_translate("AddData", "Search"))
