# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditTraitOrFeat.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditTraitOrFeatData(object):
    def setupUi(self, EditTraitOrFeatData):
        EditTraitOrFeatData.setObjectName("EditTraitOrFeatData")
        EditTraitOrFeatData.resize(558, 487)
        self.centralwidget = QtWidgets.QWidget(EditTraitOrFeatData)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.name = QtWidgets.QComboBox(self.centralwidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 8, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.type = QtWidgets.QComboBox(self.centralwidget)
        self.type.setObjectName("type")
        self.gridLayout.addWidget(self.type, 3, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 2)
        self.inputHTML = QtWidgets.QTextEdit(self.centralwidget)
        self.inputHTML.setObjectName("inputHTML")
        self.gridLayout.addWidget(self.inputHTML, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 1, 1, 2)
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setObjectName("search")
        self.gridLayout.addWidget(self.search, 1, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.url = QtWidgets.QLineEdit(self.centralwidget)
        self.url.setObjectName("url")
        self.gridLayout.addWidget(self.url, 1, 0, 1, 1)
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 8, 2, 1, 1)
        self.displayData = QtWidgets.QTextBrowser(self.centralwidget)
        self.displayData.setObjectName("displayData")
        self.gridLayout.addWidget(self.displayData, 7, 1, 1, 2)
        self.source = QtWidgets.QComboBox(self.centralwidget)
        self.source.setObjectName("source")
        self.gridLayout.addWidget(self.source, 5, 0, 1, 1)
        EditTraitOrFeatData.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditTraitOrFeatData)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 21))
        self.menubar.setObjectName("menubar")
        EditTraitOrFeatData.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(EditTraitOrFeatData)
        self.statusBar.setObjectName("statusBar")
        EditTraitOrFeatData.setStatusBar(self.statusBar)

        self.retranslateUi(EditTraitOrFeatData)
        QtCore.QMetaObject.connectSlotsByName(EditTraitOrFeatData)
        EditTraitOrFeatData.setTabOrder(self.url, self.search)
        EditTraitOrFeatData.setTabOrder(self.search, self.type)
        EditTraitOrFeatData.setTabOrder(self.type, self.inputHTML)
        EditTraitOrFeatData.setTabOrder(self.inputHTML, self.displayData)
        EditTraitOrFeatData.setTabOrder(self.displayData, self.save)

    def retranslateUi(self, EditTraitOrFeatData):
        _translate = QtCore.QCoreApplication.translate
        EditTraitOrFeatData.setWindowTitle(_translate("EditTraitOrFeatData", "MainWindow"))
        self.label.setText(_translate("EditTraitOrFeatData", "HTML data"))
        self.label_3.setText(_translate("EditTraitOrFeatData", "Input URL"))
        self.label_5.setText(_translate("EditTraitOrFeatData", "Source"))
        self.label_4.setText(_translate("EditTraitOrFeatData", "Input type"))
        self.label_2.setText(_translate("EditTraitOrFeatData", "Displayed data"))
        self.search.setText(_translate("EditTraitOrFeatData", "Search"))
        self.label_6.setText(_translate("EditTraitOrFeatData", "Input name"))
        self.save.setText(_translate("EditTraitOrFeatData", "Save"))
