# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FeatEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FeatEdit(object):
    def setupUi(self, FeatEdit):
        FeatEdit.setObjectName("FeatEdit")
        FeatEdit.resize(420, 495)
        self.centralwidget = QtWidgets.QWidget(FeatEdit)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.type = QtWidgets.QLineEdit(self.centralwidget)
        self.type.setObjectName("type")
        self.gridLayout.addWidget(self.type, 5, 0, 1, 2)
        self.source = QtWidgets.QLineEdit(self.centralwidget)
        self.source.setObjectName("source")
        self.gridLayout.addWidget(self.source, 7, 0, 1, 2)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout.addWidget(self.deleteButton, 12, 1, 1, 1)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 12, 0, 1, 1)
        self.name = QtWidgets.QComboBox(self.centralwidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 2)
        self.notes = QtWidgets.QTextBrowser(self.centralwidget)
        self.notes.setObjectName("notes")
        self.gridLayout.addWidget(self.notes, 11, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 10, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.additionalNotes = QtWidgets.QLineEdit(self.centralwidget)
        self.additionalNotes.setObjectName("additionalNotes")
        self.gridLayout.addWidget(self.additionalNotes, 3, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 2)
        FeatEdit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FeatEdit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 21))
        self.menubar.setObjectName("menubar")
        FeatEdit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FeatEdit)
        self.statusbar.setObjectName("statusbar")
        FeatEdit.setStatusBar(self.statusbar)

        self.retranslateUi(FeatEdit)
        QtCore.QMetaObject.connectSlotsByName(FeatEdit)
        FeatEdit.setTabOrder(self.name, self.additionalNotes)
        FeatEdit.setTabOrder(self.additionalNotes, self.type)
        FeatEdit.setTabOrder(self.type, self.source)
        FeatEdit.setTabOrder(self.source, self.notes)
        FeatEdit.setTabOrder(self.notes, self.closeButton)
        FeatEdit.setTabOrder(self.closeButton, self.deleteButton)

    def retranslateUi(self, FeatEdit):
        _translate = QtCore.QCoreApplication.translate
        FeatEdit.setWindowTitle(_translate("FeatEdit", "MainWindow"))
        self.label.setText(_translate("FeatEdit", "Name"))
        self.deleteButton.setText(_translate("FeatEdit", "Delete"))
        self.closeButton.setText(_translate("FeatEdit", "Close"))
        self.label_2.setText(_translate("FeatEdit", "Type"))
        self.label_3.setText(_translate("FeatEdit", "Description"))
        self.label_4.setText(_translate("FeatEdit", "Source"))
        self.label_5.setText(_translate("FeatEdit", "Notes (Specialisation, Proficiency, ...)"))
