# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GearEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GearEdit(object):
    def setupUi(self, GearEdit):
        GearEdit.setObjectName("GearEdit")
        GearEdit.resize(555, 262)
        self.centralwidget = QtWidgets.QWidget(GearEdit)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.type = QtWidgets.QLineEdit(self.centralwidget)
        self.type.setObjectName("type")
        self.gridLayout.addWidget(self.type, 1, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 3)
        self.item = QtWidgets.QLineEdit(self.centralwidget)
        self.item.setObjectName("item")
        self.gridLayout.addWidget(self.item, 3, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 3)
        self.location = QtWidgets.QLineEdit(self.centralwidget)
        self.location.setObjectName("location")
        self.gridLayout.addWidget(self.location, 5, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 2, 1, 1)
        self.weight = QtWidgets.QLineEdit(self.centralwidget)
        self.weight.setMaximumSize(QtCore.QSize(100, 16777215))
        self.weight.setObjectName("weight")
        self.gridLayout.addWidget(self.weight, 7, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 1, 1, 1)
        self.quantity = QtWidgets.QLineEdit(self.centralwidget)
        self.quantity.setMaximumSize(QtCore.QSize(100, 16777215))
        self.quantity.setObjectName("quantity")
        self.gridLayout.addWidget(self.quantity, 7, 0, 1, 1)
        self.notes = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.notes.setObjectName("notes")
        self.gridLayout.addWidget(self.notes, 1, 3, 7, 1)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout.addWidget(self.deleteButton, 8, 3, 1, 1)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 8, 0, 1, 3)
        GearEdit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GearEdit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 21))
        self.menubar.setObjectName("menubar")
        GearEdit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GearEdit)
        self.statusbar.setObjectName("statusbar")
        GearEdit.setStatusBar(self.statusbar)

        self.retranslateUi(GearEdit)
        QtCore.QMetaObject.connectSlotsByName(GearEdit)
        GearEdit.setTabOrder(self.type, self.item)
        GearEdit.setTabOrder(self.item, self.location)
        GearEdit.setTabOrder(self.location, self.quantity)
        GearEdit.setTabOrder(self.quantity, self.weight)
        GearEdit.setTabOrder(self.weight, self.notes)
        GearEdit.setTabOrder(self.notes, self.closeButton)
        GearEdit.setTabOrder(self.closeButton, self.deleteButton)

    def retranslateUi(self, GearEdit):
        _translate = QtCore.QCoreApplication.translate
        GearEdit.setWindowTitle(_translate("GearEdit", "MainWindow"))
        self.label_7.setText(_translate("GearEdit", "Notes"))
        self.label.setText(_translate("GearEdit", "Type"))
        self.label_3.setText(_translate("GearEdit", "Location"))
        self.label_4.setText(_translate("GearEdit", "Quantity"))
        self.label_2.setText(_translate("GearEdit", "Item"))
        self.label_6.setText(_translate("GearEdit", "lb. per Item"))
        self.label_5.setText(_translate("GearEdit", "Weight"))
        self.deleteButton.setText(_translate("GearEdit", "Delete"))
        self.closeButton.setText(_translate("GearEdit", "Close"))
