# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AbilityEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AbilityEdit(object):
    def setupUi(self, AbilityEdit):
        AbilityEdit.setObjectName("AbilityEdit")
        AbilityEdit.resize(332, 299)
        self.centralwidget = QtWidgets.QWidget(AbilityEdit)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 6, 0, 1, 1)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout.addWidget(self.deleteButton, 6, 1, 1, 1)
        self.notes = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.notes.setObjectName("notes")
        self.gridLayout.addWidget(self.notes, 5, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 2)
        self.type = QtWidgets.QLineEdit(self.centralwidget)
        self.type.setObjectName("type")
        self.gridLayout.addWidget(self.type, 3, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        AbilityEdit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AbilityEdit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 332, 21))
        self.menubar.setObjectName("menubar")
        AbilityEdit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AbilityEdit)
        self.statusbar.setObjectName("statusbar")
        AbilityEdit.setStatusBar(self.statusbar)

        self.retranslateUi(AbilityEdit)
        QtCore.QMetaObject.connectSlotsByName(AbilityEdit)

    def retranslateUi(self, AbilityEdit):
        _translate = QtCore.QCoreApplication.translate
        AbilityEdit.setWindowTitle(_translate("AbilityEdit", "MainWindow"))
        self.closeButton.setText(_translate("AbilityEdit", "Close"))
        self.deleteButton.setText(_translate("AbilityEdit", "Delete"))
        self.label_3.setText(_translate("AbilityEdit", "Notes"))
        self.label_2.setText(_translate("AbilityEdit", "Type (Ex, Sp, Su, ...)"))
        self.label.setText(_translate("AbilityEdit", "Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AbilityEdit = QtWidgets.QMainWindow()
    ui = Ui_AbilityEdit()
    ui.setupUi(AbilityEdit)
    AbilityEdit.show()
    sys.exit(app.exec_())
